### ISSUE TITLE
Only bold, italic text can be displayed

### ISSUE THREAD

**Issue by mnemosx** [Spoutnik97/react-native-prismic-richtext#1] opened 2021-11-01 12:10 UTC
For anything else "React is not defined" error is returned and app crashes.
H1 through H6 won't make the app crash, but no styles are applied to these elements .

**Comment by mnemosx** [comment] 2021-11-29 19:06
To add, on iOS no styles are applied at all.

**Comment by jacprada** [comment] 2021-12-09 14:48
Hey @mnemosx! It seems to me like the _React is not defined_ error is caused by a missing React dependency required by some of the functions within the `node_modules/react-native-prismic-richtext/lib/services.js` file, like for example `serializeUl`. I have not spent much time looking into it but adding a simple `import React from 'react';` in that particular file seems to prevent the error and crash, at least in the instances that I have tested.

Also, I think adding styles for individual elements should be done manually. If, for example, you want to differentiate the H3 element through a bold style, you should add it yourself to the `RichText` element styles. On both the iOS simulator and my actual device I can see the styles applied correctly.

```
          <RichText
            richText={prismicRichTextResponse}
            styles={{
              heading3: { fontWeight: 'bold' }
            }}
          />
```


@Spoutnik97 any chance you could look into the missing React dependency that is currently causing the error and crash? It prevents the library from being used when a rich text field response contains list items, for example. Happy to provide more information on the error and crash. And thank you for creating and sharing this cool package! 🙏

**Comment by bitboxer** [comment] 2022-01-03 20:49
@mnemosx @jacprada this should be fixed with the release today.

**Comment by Spoutnik97** [comment] 2022-02-01 08:38
@jacprada thanks for the issue. I will correct it today, then I will ping you when the new version is published

**Closed as completed** 2022-02-01 09:05 UTC
